#!/usr/bin/env bash
# Clinical Red Team Platform — droplet bootstrap.
#
# Brings up the attacker stack alongside the W2 AgentForge target on
# the same droplet. Mirrors W2's bootstrap pattern (see
# AgentForge/.deploy/bootstrap.sh in the companion repo).
#
# Run from inside the repo on the droplet:
#   cd /opt/redteam/repo
#   sudo bash .deploy/bootstrap.sh
#
# Idempotent — safe to re-run. On first run:
#   1. Generates /opt/redteam/.env with placeholders for required keys
#      (OpenRouter, HMAC secret pulled from W2's .env, Langfuse optional)
#   2. Writes /opt/redteam/docker-compose.yml from this repo's template
#   3. Patches /opt/agentforge/Caddyfile to add the redteam-* hostname
#   4. Reloads Caddy in the W2 stack so the new TLS cert provisions
#   5. Builds the redteam image, brings up daemon + status services
#   6. Verifies the status URL responds via curl through Caddy
#
# Required secrets — bootstrap fills HMAC from W2's .env, but the
# OpenRouter key must be set MANUALLY before first run completes:
#   OPENROUTER_API_KEY    — droplet env, or paste into /opt/redteam/.env
#
# Optional:
#   LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY
set -euo pipefail

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PUBLIC_IP="142.93.242.40"
PUBLIC_HOSTNAME="142-93-242-40.nip.io"
ATTACKER_HOSTNAME="redteam-${PUBLIC_HOSTNAME}"

DEPLOY_DIR="/opt/redteam"
REPO_DIR="${DEPLOY_DIR}/repo"
EVALS_DIR="${DEPLOY_DIR}/evals"

W2_DEPLOY_DIR="/opt/agentforge"
W2_ENV="${W2_DEPLOY_DIR}/.env"
W2_CADDYFILE="${W2_DEPLOY_DIR}/Caddyfile"

# Bootstrap-managed block markers — used to make the Caddyfile patch
# idempotent. Same string as the BEGIN/END comments in Caddyfile.fragment.
CADDY_BEGIN_MARKER="# BEGIN clinical-redteam fragment"
CADDY_END_MARKER="# END clinical-redteam fragment"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() { echo "==> $*" >&2; }
die() { echo "!!! $*" >&2; exit 1; }

require_root() {
    [[ "$EUID" -eq 0 ]] || die "Must run as root (use sudo bash $0)"
}

require_w2_running() {
    # W2 must be up before we can attach to its network or patch its Caddyfile.
    [[ -d "$W2_DEPLOY_DIR" ]] || die "W2 deployment not found at $W2_DEPLOY_DIR. Deploy AgentForge first."
    [[ -f "$W2_ENV" ]] || die "W2 .env missing at $W2_ENV"
    [[ -f "$W2_CADDYFILE" ]] || die "W2 Caddyfile missing at $W2_CADDYFILE"
    docker network ls --format '{{.Name}}' | grep -q '^agentforge_default$' \
        || die "W2 docker network 'agentforge_default' not found. Bring W2 up first: cd $W2_DEPLOY_DIR && docker compose up -d"
}

require_repo_in_place() {
    [[ -d "$REPO_DIR/.git" ]] || die "Repo not found at $REPO_DIR. Run: git clone <url> $REPO_DIR"
}

# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

require_root
require_w2_running
require_repo_in_place

mkdir -p "$DEPLOY_DIR" "$EVALS_DIR"

# Writable subdirs that get bind-mounted into the daemon + status
# containers. Create them up-front and chown to the in-container user
# (uid 1000 = `redteam` per .deploy/Dockerfile). Without this the
# container can't mkdir new run-id directories under results/ — it
# inherits the root-owned mount and PermissionErrors on first write.
mkdir -p "$EVALS_DIR/results" "$EVALS_DIR/vulnerabilities" "$EVALS_DIR/regression"
# F23: regression/ is bind-mounted into both daemon (rw — F17 auto-promote
# writes here) and status (ro). Without the mkdir + chown the daemon
# PermissionErrors on the first F17 promotion attempt (we hit this exact
# pattern before with results/ and vulnerabilities/).
chown -R 1000:1000 "$EVALS_DIR"

# 1. Generate /opt/redteam/.env on first run; preserve across re-runs.
#    Pulls HMAC secret from W2's .env so the attacker's signed requests
#    match the target's verifier. OpenRouter key is the only thing the
#    operator must set manually.
if [[ ! -f "${DEPLOY_DIR}/.env" ]]; then
    log "Generating ${DEPLOY_DIR}/.env (first run)"
    # Source W2's HMAC secret. `set -a` exports everything sourced.
    HMAC_FROM_W2=$(grep '^OPENEMR_HMAC_SECRET=' "$W2_ENV" | cut -d= -f2- | tr -d '"')
    [[ -n "$HMAC_FROM_W2" ]] || die "Could not read OPENEMR_HMAC_SECRET from $W2_ENV"

    cat > "${DEPLOY_DIR}/.env" <<EOF
# Generated by .deploy/bootstrap.sh — re-run to overwrite missing fields.
# This file lives outside the repo (/opt/redteam/.env, mode 600).

# === Target (matches W2 AgentForge deployment) ===
# Pulled from /opt/agentforge/.env at bootstrap time. If you rotate
# the W2 HMAC secret, re-run this bootstrap so both stacks stay in sync.
RED_TEAM_TARGET_HMAC_SECRET=${HMAC_FROM_W2}

# === OpenRouter — REQUIRED, set manually ===
# Get a key at https://openrouter.ai/keys. Without this, the Red Team
# Agent + Judge Agent + Doc Agent all fail on their first LLM call.
OPENROUTER_API_KEY=

# === Model routing per agent tier ===
# Per-tier primary + comma-separated fallback list. Fallback fires on
# 429/5xx/connect/404. Names match openrouter.py:50-60 dispatch dict.
#
# Red Team — needs minimal safety training to probe; deepseek is the
# least-aligned at OpenRouter pricing tier we use. llama + haiku are
# pragmatic fallbacks if deepseek rate-limits.
RED_TEAM_MODEL=deepseek/deepseek-chat
RED_TEAM_FALLBACK_MODELS=meta-llama/llama-3.1-70b-instruct,anthropic/claude-haiku-4.5

# Judge — needs reasoning quality + consistent scoring. Sonnet is the
# anchor; haiku fallback covers Sonnet rate limits without dropping
# quality off a cliff for the rubric matching task.
JUDGE_MODEL=anthropic/claude-sonnet-4-5
JUDGE_FALLBACK_MODEL=anthropic/claude-haiku-4.5

# Documentation — structured-output task; haiku is fast + cheap + good
# enough at following the ARCH §12.4 template.
DOCUMENTATION_MODEL=anthropic/claude-haiku-4.5
DOCUMENTATION_FALLBACK_MODEL=anthropic/claude-sonnet-4-5

# === Cost guard (per-session ceiling, USD) ===
# Daemon halts when cumulative spend crosses this. Conservative default
# for unsupervised operation; raise if you want longer runs.
MAX_SESSION_COST_USD=5.00

# === Daily budget gate (F19, rolling-24h aggregate, USD) ===
# Daemon refuses to START a new run if the sum of total_usd across all
# cost-ledger.json files in evals/results/ over the last 24h is >= this
# value. Pairs with restart: on-failure:3 — gate fires as exit 8, which
# is non-zero so on-failure briefly retries, then gives up at the cap.
# Captures OpenRouter-side spend only; the target-side LLM provider
# (Anthropic, on the W2 Co-Pilot side) is not visible to this gate.
MAX_DAILY_COST_USD=50.00

# === Langfuse — OPTIONAL ===
# Without these, inter-agent traces don't emit but everything else runs.
# Get keys at https://cloud.langfuse.com.
LANGFUSE_PUBLIC_KEY=
LANGFUSE_SECRET_KEY=
LANGFUSE_HOST=https://cloud.langfuse.com

# === Operational ===
LOG_LEVEL=INFO
EOF
    chmod 600 "${DEPLOY_DIR}/.env"
    log "WARNING: set OPENROUTER_API_KEY in ${DEPLOY_DIR}/.env before continuing"
    log "    sudo nano ${DEPLOY_DIR}/.env"
fi

# 1b. Patch any missing model vars idempotently. .env files generated by
#    earlier bootstrap versions used RED_TEAM_TIER1_MODEL / TIER2 / TIER3
#    names that openrouter.py never reads. Append the correct names if
#    they're absent, preserving everything the operator has already set
#    (OPENROUTER_API_KEY, HMAC, etc.).
_patch_env_var() {
    local var="$1" default="$2"
    if ! grep -q "^${var}=" "${DEPLOY_DIR}/.env"; then
        echo "${var}=${default}" >> "${DEPLOY_DIR}/.env"
        log "Appended ${var} to .env"
    fi
}
_patch_env_var "RED_TEAM_MODEL" "deepseek/deepseek-chat"
_patch_env_var "RED_TEAM_FALLBACK_MODELS" "meta-llama/llama-3.1-70b-instruct,anthropic/claude-haiku-4.5"
_patch_env_var "JUDGE_MODEL" "anthropic/claude-sonnet-4-5"
_patch_env_var "JUDGE_FALLBACK_MODEL" "anthropic/claude-haiku-4.5"
_patch_env_var "DOCUMENTATION_MODEL" "anthropic/claude-haiku-4.5"
_patch_env_var "DOCUMENTATION_FALLBACK_MODEL" "anthropic/claude-sonnet-4-5"
# F19 daily budget gate. Idempotent patch so existing .env files from
# previous bootstrap runs pick up the new gate without manual edits.
_patch_env_var "MAX_DAILY_COST_USD" "50.00"

# 2. Compose file is referenced IN-PLACE from the repo.
#    Earlier versions copied it to /opt/redteam/, but that broke the
#    `context: ..` relative path in the compose file's build directive
#    (`..` from /opt/redteam/ → /opt/, which doesn't have .deploy/Dockerfile).
#    Keeping the compose file at $REPO_DIR/.deploy/ means `context: ..`
#    resolves to $REPO_DIR — correct.
#
#    Set the in-repo compose path FIRST so later steps can reference it.
COMPOSE_FILE="${REPO_DIR}/.deploy/docker-compose.redteam.yml"

#    Remove any stale copy from a previous (broken) bootstrap run.
if [[ -f "${DEPLOY_DIR}/docker-compose.yml" ]]; then
    log "Removing stale ${DEPLOY_DIR}/docker-compose.yml (now referenced in-place from repo)"
    rm -f "${DEPLOY_DIR}/docker-compose.yml"
fi

# 3. Patch W2's Caddyfile to add the attacker hostname.
#    Idempotent — checks for the marker comment, only appends if absent.
if grep -qF "$CADDY_BEGIN_MARKER" "$W2_CADDYFILE"; then
    log "Caddyfile already patched — replacing managed block"
    # Replace the existing managed block with the current fragment so
    # bootstrap can roll forward config changes without manual edits.
    # awk-based "delete between markers" pattern.
    awk -v begin="$CADDY_BEGIN_MARKER" -v end="$CADDY_END_MARKER" '
        $0 ~ begin { skip = 1 }
        !skip { print }
        $0 ~ end { skip = 0; next }
    ' "$W2_CADDYFILE" > "${W2_CADDYFILE}.tmp"
    mv "${W2_CADDYFILE}.tmp" "$W2_CADDYFILE"
fi

log "Appending attacker Caddyfile fragment"
{
    echo ""
    cat "${REPO_DIR}/.deploy/Caddyfile.fragment"
} >> "$W2_CADDYFILE"

# 4. Reload Caddy in the W2 stack so the new hostname picks up.
#    `caddy reload` is graceful — existing connections continue, new
#    config takes effect for new requests.
log "Reloading Caddy in W2 stack"
docker compose -f "${W2_DEPLOY_DIR}/docker-compose.yml" exec -T caddy \
    caddy reload --config /etc/caddy/Caddyfile \
    || die "Caddy reload failed — check Caddyfile syntax: docker compose -f ${W2_DEPLOY_DIR}/docker-compose.yml exec caddy caddy validate --config /etc/caddy/Caddyfile"

# 5. Build attacker image, bring up the stack.
#    Reference the compose file in-place from the repo. Default project
#    directory becomes the compose file's directory ($REPO_DIR/.deploy/),
#    so `context: ..` in the compose file correctly resolves to $REPO_DIR.
log "Building attacker image (~2-3 min on first build)"
docker compose -f "$COMPOSE_FILE" \
    --env-file "${DEPLOY_DIR}/.env" \
    build

log "Starting attacker stack"
docker compose -f "$COMPOSE_FILE" \
    --env-file "${DEPLOY_DIR}/.env" \
    up -d

# 6. Smoke-verify the status URL responds through Caddy.
#    Caddy provisions a fresh Let's Encrypt cert on first request to a
#    new hostname; first hit can take 5-15s. Retry loop covers it.
log "Verifying status URL through Caddy (up to 60s for TLS cert provisioning)"
for i in $(seq 1 12); do
    if curl -fsS --max-time 5 "https://${ATTACKER_HOSTNAME}/health" >/dev/null 2>&1; then
        log "Status URL live: https://${ATTACKER_HOSTNAME}/"
        break
    fi
    if [[ $i -eq 12 ]]; then
        log "WARNING: status URL not responding after 60s. Check logs:"
        log "    docker compose -f ${COMPOSE_FILE} logs redteam-status"
        log "    docker compose -f ${W2_DEPLOY_DIR}/docker-compose.yml logs caddy"
    fi
    sleep 5
done

# 7. Summary.
cat <<EOF

=============================================
Clinical Red Team Platform — Deployment Live
=============================================

Target URL (W2):     https://${PUBLIC_HOSTNAME}
Attacker URL (W3):   https://${ATTACKER_HOSTNAME}

Operational commands:
  Daemon logs:   docker compose -f ${COMPOSE_FILE} logs -f redteam-daemon
  Status logs:   docker compose -f ${COMPOSE_FILE} logs -f redteam-status
  Daemon stop:   docker compose -f ${COMPOSE_FILE} stop redteam-daemon
  Daemon start:  docker compose -f ${COMPOSE_FILE} start redteam-daemon
  Full restart:  docker compose -f ${COMPOSE_FILE} restart

Update from local:
  cd ${REPO_DIR} && git pull
  sudo bash .deploy/bootstrap.sh   # idempotent; safe to re-run

=============================================

EOF

# Tail the first few daemon log lines so the operator can see signs of
# life without copy-pasting commands.
#
# Pass --env-file so compose doesn't warn about unset ${VAR}s during the
# re-parse — the container itself already has the vars from the earlier
# `compose up`, this is just to keep the parse-time substitution clean.
log "First 30 lines of daemon log (Ctrl-C to stop tailing):"
docker compose -f "${COMPOSE_FILE}" \
    --env-file "${DEPLOY_DIR}/.env" \
    logs --tail=30 redteam-daemon || true
